name: Run tests

on: [push]

env:
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World"
      - uses: actions/checkout@v2
        with:
          ref: 'feat/pr-test'
          fetch-depth: 0
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git tag "$COMMIT_SHA"
          git push --tags
