name: Run tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Hello World"
      - uses: actions/checkout@v2
        with:
          ref: 'feat/pr-test'
          fetch-depth: 0
      - run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git merge origin/feat/pr-test-merge
          git push origin
        if: github.ref_name == 'feat/pr-test-merge'
